### ISSUE TITLE
Selection of multiple clients with CTRL/STRG key doesn't work

### ISSUE THREAD

**Issue by J-U-B** [opsi-org/opsi-configed#1]
### Environment
* `opsi-configed` version: 4.3.0.11 (2023-04-18) 
* Java version:  11.0.19+7-LTS (Amazon Corretto)
* OS: Ubuntu 20.04.5 LTS

### Error description:
The attempt to select multiple clients from the client list by holding down the CTRL/STRG key fails.  
Only the last clicked client is selected.

**Comment by J-U-B** [comment]
...same with:
* Windows 10  2021 LTSC
* Java version: 17.0.7+7-LTS (Amazon Corretto)

**Comment by nilssotto** [comment]
The problem should be solved now.
